name: Build and Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install build tools
      run: pip install setuptools wheel build pybind11

    - name: Auto-detect project directory
      id: detect
      run: |
        DIR=$(dirname $(find . -type f \( -name "pyproject.toml" -o -name "setup.py" \) | head -n 1))
        echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
        echo "Detected project directory: $DIR"

    - name: Show project structure
      run: ls -R $PROJECT_DIR

    - name: Build source distribution only (PyPI-safe)
      run: |
        cd "$PROJECT_DIR"
        python setup.py sdist

    - name: Show dist files
      run: |
        ls -R $PROJECT_DIR/dist

    - name: Publish to PyPI (Trusted Publishing)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ env.PROJECT_DIR }}/dist
